import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link';
import Model from '../component/model';
import { blogPost } from '../lib/Blog_data';
import DataFatch from './dataFatching';
import LoginFrom from './LoginForm';
import ReuseFrom from './reuseForm';
import Effacting from './useEfact';
// import styles from '../styles/Home.module.css'
import UseEffect from './UseEffect';
import VideoSection from './video';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>ddfgdg</h1>
      <UseEffect />
      <Model/>
      {/* <VideoSection/> */}
      <Effacting/>
      {/* <DataFatch/> */}


      <div>
        {blogPost.map((item) => (
          <div key={item.slug}>
            <Link href={`/blog_slug/${item.slug}`}><a><h1>{item.title}</h1></a></Link>
            <h5>{item.date}</h5>
            <p>{item.content}</p>
          </div>
        ))}
      </div>

      <ReuseFrom/>
      <LoginFrom />

    </div>
  )
}
